version: '3.8'

services:
  frontend:
    build: .
    container_name: spectrogram-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5000}
    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge